un-fscking some of the ASI, starting to un-bork the workspace. What a cluster.

diff --git a/w2shell b/w2shell
--- a/w2shell
+++ b/w2shell
@@ -1,2 +1,21 @@
-./v8 Worlds2_Library.js ometa-rhino.js Worlds2.js arrays.wjs $@ --shell
+#!/bin/bash
 
+JSCPATH='/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc'
+D8PATH=$(type -P d8)
+JPATH=$(type -P java)
+RUNNER=''
+
+# FIXME(slightlyoff): Add option parsing to support explicit runtime selection.
+
+if   [ $D8PATH ]  && [ -x $D8PATH ]; then
+  RUNNER='d8 --harmony';
+elif [ $JSCPATH ] && [ -x $JSCPATH ]; then
+  RUNNER=$JSCPATH;
+elif [ $JPATH ]   && [ -x $JPATH ]; then
+  RUNNER='$JPATH -classpath ../util/js.jar org.mozilla.javascript.tools.shell.Main';
+else
+  echo "FAILED: No JavaScript Runtime Found! Please install Java or the V8 Shell (d8) and add them to your \$PATH"
+  exit 1;
+fi
+
+$RUNNER Worlds2_Library.js ometa-rhino.js Worlds2.js arrays.wjs $@ --shell
